NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.university.clemson.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.university.clemson.com-cert.pem
    OrganizationalUnitIdentifier: peer
