version: '2'

services:
  ca:
    container_name: ca.student.clemson.com
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-student
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/ca.student.clemson.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/1b63607d2ccbf9a4a98e71e8ec7f9f62ff43b0f744bd3c022201316ee0d805ae_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/ca.student.clemson.com-cert.pem --ca.keyfile /etc/hyperledger/1b63607d2ccbf9a4a98e71e8ec7f9f62ff43b0f744bd3c022201316ee0d805ae_sk -b admin:adminpw -d'
    volumes:
      - ../channel-artifacts/certs/peerOrganizations/student.clemson.com/ca:/etc/hyperledger


  peer0-db:
    container_name: peer0-db.student.clemson.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=studentpeer0admin
      - COUCHDB_PASSWORD=pass

  peer1-db:
    container_name: peer1-db.student.clemson.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=studentpeer1admin
      - COUCHDB_PASSWORD=pass


  peer0:
    container_name: peer0.student.clemson.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.student.clemson.com
      - CORE_PEER_ADDRESS=peer0.student.clemson.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.student.clemson.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.student.clemson.com:7051
      - CORE_PEER_LOCALMSPID=StudentMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0-db.student.clemson.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=studentpeer0admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pass
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/users/Admin@student.clemson.com/msp

      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/fabric/users/Admin@student.clemson.com/tls/ca.crt
      - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/fabric/users/Admin@student.clemson.com/tls/client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/fabric/users/Admin@student.clemson.com/tls/client.key
    volumes:
        - /var/run/:/host/var/run/
        - ../channel-artifacts/certs/peerOrganizations/student.clemson.com/peers/peer0.student.clemson.com/msp:/etc/hyperledger/fabric/msp
        - ../channel-artifacts/certs/peerOrganizations/student.clemson.com/peers/peer0.student.clemson.com/tls:/etc/hyperledger/fabric/tls
        - ../channel-artifacts/certs/peerOrganizations/student.clemson.com/users:/etc/hyperledger/fabric/users
    ports:
      - 9051:7051
      - 9053:7053

  peer1:
    container_name: peer1.student.clemson.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.student.clemson.com
      - CORE_PEER_ADDRESS=peer1.student.clemson.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.student.clemson.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.student.clemson.com:7051
      - CORE_PEER_LOCALMSPID=StudentMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1-db.student.clemson.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=studentpeer1admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pass
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/users/Admin@student.clemson.com/msp
      #
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/fabric/users/Admin@student.clemson.com/tls/ca.crt
      - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/fabric/users/Admin@student.clemson.com/tls/client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/fabric/users/Admin@student.clemson.com/tls/client.key
    volumes:
        - /var/run/:/host/var/run/
        - ../channel-artifacts/certs/peerOrganizations/student.clemson.com/peers/peer1.student.clemson.com/msp:/etc/hyperledger/fabric/msp
        - ../channel-artifacts/certs/peerOrganizations/student.clemson.com/peers/peer1.student.clemson.com/tls:/etc/hyperledger/fabric/tls
        - ../channel-artifacts/certs/peerOrganizations/student.clemson.com/users:/etc/hyperledger/fabric/users
    ports:
      - 10051:7051
      - 10053:7053
